### ISSUE TITLE
Global installation of Composer plugin

### ISSUE THREAD

**Issue by mcaskill** [szepeviktor/composer-envato#13]
> This Composer plugin must be installed globally as it adds a virtual package repository.

I see that this [notice was present early on](https://github.com/szepeviktor/composer-envato/commit/8abbc529cec6c0ed6402b8a6880a94426978b7ef).

Out of curiosity, I browsed the source code then I tested this plugin as a project requirement instead of installing it globally. It appears to work well.

What about this plugin requires it to be globally installed?

I have not looked at earlier versions; this was probably a necessity with Composer v1.

Furthermore, if this plugin can be safely installed per project, could the Envato personal access token be optionally outsourced to an environment variable (such as from a `.env` file loaded with [vlucas/phpdotenv](https://github.com/vlucas/phpdotenv))?

**Comment by szepeviktor** [comment]
I do not know!
What are your wishes?

**Comment by mcaskill** [comment]
Well, maybe the README can mention that the plugin can be installed either globally or per project, or left unchanged.

I was about to test adding support for [Dotenv](https://github.com/vlucas/phpdotenv) to fetch the token from from an environment variable. What do you think?

**Comment by szepeviktor** [comment]
I know there is a technology in Composer v2 to execute plugins early.
I leave this 100% up to you! Just leave a short notice in README that with Composer v2 global installation might be not necessary.

**Comment by szepeviktor** [comment]
Be aware! There is not a single high quality plugin/theme on Envato.

**Comment by mcaskill** [comment]
I'm, sadly, well aware of the quality of plugins and themes on Envato and across the WordPress ecosystem.

**Comment by mcaskill** [comment]
Resolved in #14
