### ISSUE TITLE
Installing embedded plugins in Avada

### ISSUE THREAD

**Issue by dlecan** [szepeviktor/composer-envato#5]
Thank you for this plugin, installation of Avada theme works great on my Bedrock WordPress website.

But ... it is very hard to install additional plugins.
For example, I get an error when I try install a plugin:

```
[Composer\Downloader\TransportException]                                                                                     
  The "https://api.envato.com/v3/market/buyer/download?item_id=1362246" file could not be downloaded (HTTP/1.1 404 Not Found)
```

The id of copied/pasted from the README file.

Is it an issue with the id of the plugin, a missing role of my access token?
How/where to get reliable plugins `item-id` and/or package names such as `layerslider-plugin`?

Thank you!

**Comment by szepeviktor** [comment]
Hello Damien! :)

- you find the itemID in you purchase receipt thingy and in the product URL: https://codecanyon.net/item/kreatura-slider-plugin-for-wordpress/1362246
- a layerslider license need to be on your account! see your download on CodeCanyon

**Comment by szepeviktor** [comment]
![kép](https://user-images.githubusercontent.com/952007/76957277-c6471b80-6915-11ea-8052-b9a13c6c13c8.png)

**Comment by szepeviktor** [comment]
> package names such as `layerslider-plugin`

You choose package name! It is entirely made up.

**Comment by dlecan** [comment]
Thank you!

What I understand:
- the link between Composer and Envato is done only with `item-id` and package "names" can be chosen just for humans
- 404 means "access denied", you have to pay :)
However, `LayerSlider WP` is in the list of [Avada’s Bundled Plugins](https://theme-fusion.com/documentation/avada/install-update/plugin-installation/), so it should possible for me to install it, shouldn't it?

Do you know where to find the `item-id` of "Fusion Core" and "Fusion Builder" plugins?

**Comment by szepeviktor** [comment]
>     * package "names" can be chosen just for humans

actually Composer does need a name for each package

**Comment by szepeviktor** [comment]
> Do you know where to find the item-id of "Fusion Core" and "Fusion Builder" plugins?

I've started a project for downloading WP plugins from the manufacturer of Avada.
See `class-avada-remote-installer.php` in Avada.

Could be called `composer-theme-fusion`:

1. get_plugins: "theme-fusion/" + if("external_url" === '') "name"
2. request_download: nonce
3. ZIP URL = get_download

plugins

**Comment by dlecan** [comment]
> Would you like to contribute?
Yes

**Comment by dlecan** [comment]
>> Do you know where to find the item-id of "Fusion Core" and "Fusion Builder" plugins?

>I've started a project for downloading WP plugins from the manufacturer of Avada.

So it's not possible?

**Comment by szepeviktor** [comment]
> So it's not possible?

Yes it is. I've made the above sketch only, no more progress. Up to now :)

**Comment by dlecan** [comment]
Ok, i've understand, I can find plugin item-ids from the Theme fusion API with the request you have provided above

**Comment by szepeviktor** [comment]
I suspect those IDs have nothing to do with Envato.

**Comment by dlecan** [comment]
ah ok, so we need another composer plugin, such as `composer-theme-fusion` to do something equivalent as `composer-envato`?

**Comment by szepeviktor** [comment]
yes, but this time only the ThemeFusion token is necessary in config.json

**Comment by szepeviktor** [comment]
```
$ wget -qO- 'https://updates.theme-fusion.com/?avada_action=get_plugins&avada_version=5.9.0' | jq -r 'to_entries[].value.slug'
fusion-core
fusion-builder
fusion-white-label-branding
convertplug
advanced-custom-fields-pro
LayerSlider
revslider
pwa
woocommerce
the-events-calendar
wordpress-seo
leadin
contact-form-7
bbpress
```

so package names will look like `themefusion/fusion-core`

**Comment by szepeviktor** [comment]
@dlecan Would you give it a try? Its structure would be the same as this one.

**Comment by dlecan** [comment]
Yes, I will try

**Comment by dlecan** [comment]
A new plugin or en enhancement of your one?

**Comment by szepeviktor** [comment]
Of course a new one :)  dlecan/composer-themefusion

**Comment by szepeviktor** [comment]
```json
"require": {
  "szepeviktor/composer-envato": "^0.1.2"
}
```

**Comment by szepeviktor** [comment]
btw I've contacted ThemeFusion to support this development

**Comment by szepeviktor** [comment]
@dlecan Have you started a draft or something?

**Comment by szepeviktor** [comment]
I've written an MVP.
Publishing....

**Comment by dlecan** [comment]
> Have you started a draft or something?

Not yet :-)

I will try your new plugin

You are more comfortable than me
