### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by jgreys** [szepeviktor/composer-envato#6]
For some items, it returns the following message: "Item is not a Wordpress theme or plugin, or the author has provided no theme/plugin attachment" when it requests the item version (https://api.envato.com/v3/market/catalog/item-version?id=XXX)

Is there any fix planned?

Thanks for the great work! 👍

**Comment by szepeviktor** [comment]
Thank you for your report @jgreys!

If Envato states that this _Item is not a Wordpress theme or plugin_ then we cannot proceed 👍 
Please ask Envato support to resolve this.

- Are you sure your Envato API token has access to that item?
- Is that item a product for WordPress?

**Comment by jgreys** [comment]
Thanks for your prompt reply!

- Yes.
- It's a WordPress plugin, but it looks like the author did not provide it as such :(
- Sure! Here is it: https://codecanyon.net/item/layered-popups-for-wordpress/5978263

**Comment by szepeviktor** [comment]
Please contact Envato Support. I'm curious what is the situation!

**Comment by jgreys** [comment]
Quick update. Looks like the plugin team doesn't want to make any changes because the updates have to be done from their own server. I haven't heard from them since my last message. I think you can close the issue. 😣

**Comment by szepeviktor** [comment]
All right.

Thank you for the update.
