### ISSUE TITLE
Composer-envanto is not compatible with composer 2

### ISSUE THREAD

**Issue by wavehamza** [szepeviktor/composer-envato#7]
Hello Would like to know if you are still maintaining this solution :) because it saves life.

I couldn't install it using composer 2 + PHP 7.4.

**Comment by szepeviktor** [comment]
Actually I don't.
But after reading your kind message I do.
Although I will switch from v1 to v2 in a major release.

**Comment by wavehamza** [comment]
Glad reading your quick feedback :) 

Let me know if i can help or be useful for testing or whatever to keep your idea alive !!!

Best regards.

**Comment by szepeviktor** [comment]
Please prepare for PHP upgrade: `"php": "^7.4 || ^8.0"`

**Comment by szepeviktor** [comment]
Please test `dev-master`!

**Comment by wavehamza** [comment]
Hello Viktor,

I have only access to one branch that is the master. I couldn't find a
dev-master.

Would you point me in the right direction?

Thanks. Regards


Le sam. 23 janv. 2021 à 14:08, Viktor Szépe <notifications@github.com> a
écrit :

**Comment by wavehamza** [comment]
[image: Capture d’écran 2021-01-23 à 14.12.15.png]

**Comment by wavehamza** [comment]
Installation works like charm thank you a millions, but following the steps and running composer install/update again didn't download the theme from Envanto. (i may be doing something wrong).

**Comment by szepeviktor** [comment]
Fixed in v0.2.0

**Comment by szepeviktor** [comment]
> running composer install/update again didn't download the theme from Envanto

Please read  #2

**Comment by wavehamza** [comment]
I found your answer here [#SOF](https://stackoverflow.com/questions/33937036/install-wordpress-envato-plugin-with-composer-json) very useful =) you Rock!
