### ISSUE TITLE
Error: Declaration of SzepeViktor\Composer\Envato\EnvatoPackage::getDistType() must be compatible with Composer\Package\Package::getDistType(): ?string in /var/www/html/vendor/szepeviktor/composer-envato/src/EnvatoPackage.php on line 53

### ISSUE THREAD

**Issue by soenkesmiletzki** [szepeviktor/composer-envato#8]
Hello,
I try to install your composer-envato, but it doesnt work :-(
I extended the composer.json at the config array like:

        "envato": {
            "token": "PERSONAL-TOKEN",
            "packages": {
                "envato/avada-theme": {
                    "item-id": 2833226,
                    "type": "wordpress-theme"
                }
            }
        }

But after this I get an error:

PHP Fatal error:  Declaration of SzepeViktor\Composer\Envato\EnvatoPackage::getDistType() must be compatible with Composer\Package\Package::getDistType(): ?string in /var/www/html/vendor/szepeviktor/composer-envato/src/EnvatoPackage.php on line 53

Fatal error: Declaration of SzepeViktor\Composer\Envato\EnvatoPackage::getDistType() must be compatible with Composer\Package\Package::getDistType(): ?string in /var/www/html/vendor/szepeviktor/composer-envato/src/EnvatoPackage.php on line 53

Any Idea?

**Comment by szepeviktor** [comment]
Hello @soenkesmiletzki! 👋🏻 

You must have Composer v2.
This package was written for v1.

Please consider contributing.

**Comment by soenkesmiletzki** [comment]
Oh, very fast reply, thanks a lot.

I'm using Composer 2.3.10 and I'm using 0.2.0:

"szepeviktor/composer-envato": "^0.2.0"

**Comment by szepeviktor** [comment]
Actually I do not know anything about this package.
It was written for 1 client.

Please consider sending a PR.

**Comment by szepeviktor** [comment]
It turns out v0.2.0 supports Composer v2.
https://github.com/szepeviktor/composer-envato/compare/v0.1.2...v0.2.0

A small fix would resolve your issue!

**Comment by soenkesmiletzki** [comment]
Sounds great, but how to do this?

**Comment by szepeviktor** [comment]
Simply by sending a Pull Request.

**Comment by szepeviktor** [comment]
I think latest PHPStan will show every problem.

**Comment by soenkesmiletzki** [comment]
sorry, I dont know :-(

**Comment by szepeviktor** [comment]
Do you mean I would work on the problem?

**Comment by DannyTaki** [comment]
I was receiving that same error, but after updating Composer to the latest version it went away, but after creating the config.json and adding the package to my project's composer.json and running `composer update`, composer returned an error that it couldn't find that package.

![image](https://user-images.githubusercontent.com/10076553/219458268-b00343bd-476e-43bd-96f2-66cd20134e80.png)


![image](https://user-images.githubusercontent.com/10076553/219458231-ff3e9ad7-32b5-4253-a86b-ed8fbb59a480.png)

**Comment by DannyTaki** [comment]
> I think latest PHPStan will show every problem.

Running PHPStan, within your codebase should show errors that need be resolved? Going to try this

**Comment by DannyTaki** [comment]
![image](https://user-images.githubusercontent.com/10076553/219459596-c48ea225-138a-4f40-80ee-86bc990d2081.png)

**Comment by szepeviktor** [comment]
Fixed in #10
